// <auto-generated>
// This code was automatically generated. Do not modify it.
// </auto-generated>

using xMap;

namespace xMap
{
    public static class Mapper
    {
        public static string ToDto(this string source)
        {
            return "Dto";
        }
    }
}