using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using xMap.Tools.Contracts;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace xMap.Generation.CommentSection;

internal class CommentSectionLink : ILink
{
    public ILink Next { get; set; } = null!;

    public void Process(SourceProductionContext context, SemanticModel semanticModel, CompilationUnitSyntax source)
    {
        source = source
            .WithLeadingTrivia(
                Comment("// <auto-generated>"),
                Comment("// This code was automatically generated. Do not modify it."),
                Comment("// </auto-generated>"))
            .NormalizeWhitespace();

        Next?.Process(context, semanticModel, source);
    }
}